import ISO6391 from 'iso-639-1';
export const genresOption = [
	{ value: 'History', label: 'History' },
	{ value: 'Family', label: 'Family' },
	{ value: 'Adventure', label: 'Adventure' },
	{ value: 'Romance', label: 'Romance' },
	{ value: 'Comedy', label: 'Comedy' },
	{ value: 'Horror', label: 'Horror' },
	{ value: 'Crime', label: 'Crime' },
	{ value: 'Fantasy', label: 'Fantasy' },
	{ value: 'Mystery', label: 'Mystery' },
	{ value: 'Animation', label: 'Animation' },
	{ value: 'Drama', label: 'Drama' },
	{ value: 'Music', label: 'Music' },
	{ value: 'War', label: 'War' },
	{ value: 'TV Movie', label: 'TV Movie' },
	{ value: 'Action', label: 'Action' },
	{ value: 'Western', label: 'Western' },
	{ value: 'Foreign', label: 'Foreign' },
	{ value: 'Documentary', label: 'Documentary' },
	{ value: 'Thriller', label: 'Thriller' },
	{ value: 'Science Fiction', label: 'Science Fiction' }
];

export const languages = [
	{ value: 'no', label: ISO6391.getName('no') },
	{ value: 'ru', label: ISO6391.getName('ru') },
	{ value: 'fi', label: ISO6391.getName('fi') },
	{ value: 'bg', label: ISO6391.getName('bg') },
	{ value: 'fr', label: ISO6391.getName('fr') },
	{ value: 'sl', label: ISO6391.getName('sl') },
	{ value: 'sq', label: ISO6391.getName('sq') },
	{ value: 'sr', label: ISO6391.getName('sr') },
	{ value: 'sv', label: ISO6391.getName('sv') },
	{ value: 'kn', label: ISO6391.getName('kn') },
	{ value: 'ko', label: ISO6391.getName('ko') },
	//	{ value: 'cn', label: ISO6391.getName('cn') },
	{ value: 'ta', label: ISO6391.getName('ta') },
	{ value: 'cs', label: ISO6391.getName('cs') },
	{ value: 'te', label: ISO6391.getName('te') },
	{ value: 'pa', label: ISO6391.getName('pa') },
	{ value: 'th', label: ISO6391.getName('th') },
	{ value: 'tl', label: ISO6391.getName('tl') },
	{ value: 'pl', label: ISO6391.getName('pl') },
	{ value: 'he', label: ISO6391.getName('he') },
	{ value: 'da', label: ISO6391.getName('da') },
	{ value: 'tr', label: ISO6391.getName('tr') },
	{ value: 'de', label: ISO6391.getName('de') },
	{ value: 'hi', label: ISO6391.getName('hi') },
	{ value: 'pt', label: ISO6391.getName('pt') },
	{ value: 'lt', label: ISO6391.getName('lt') },
	{ value: 'lv', label: ISO6391.getName('lv') },
	{ value: 'hr', label: ISO6391.getName('hr') },
	{ value: 'hu', label: ISO6391.getName('hu') },
	{ value: 'uk', label: ISO6391.getName('uk') },
	{ value: 'id', label: ISO6391.getName('id') },
	{ value: 'ur', label: ISO6391.getName('ur') },
	{ value: 'ml', label: ISO6391.getName('ml') },
	{ value: 'ab', label: ISO6391.getName('ab') },
	{ value: 'mr', label: ISO6391.getName('mr') },
	{ value: 'ms', label: ISO6391.getName('ms') },
	{ value: 'el', label: ISO6391.getName('el') },
	{ value: 'en', label: ISO6391.getName('en') },
	{ value: 'is', label: ISO6391.getName('is') },
	{ value: 'it', label: ISO6391.getName('it') },
	{ value: 'zh', label: ISO6391.getName('zh') },
	{ value: 'es', label: ISO6391.getName('es') },
	{ value: 'et', label: ISO6391.getName('et') },
	{ value: 'eu', label: ISO6391.getName('eu') },
	{ value: 'ar', label: ISO6391.getName('ar') },
	{ value: 'vi', label: ISO6391.getName('vi') },
	{ value: 'ja', label: ISO6391.getName('ja') },
	{ value: 'ne', label: ISO6391.getName('ne') },
	{ value: 'fa', label: ISO6391.getName('fa') },
	{ value: 'ro', label: ISO6391.getName('ro') },
	{ value: 'nl', label: ISO6391.getName('nl') }
];
